### ISSUE TITLE
Explanation about parameters 

### ISSUE THREAD

**Issue by bratao** [timvieira/vocrf#2]
Hello,

@timvieira, could you please do a quick explanation about the parameters ? I'm struggling to understand it from the code. 

--initial-order
--max-order
--inner-iterations
--outer-iterations
--budget
--context-count

Thank you!

**Comment by timvieira** [comment]
Oh boy! I just noticed this issue. Sorry to leave it so long. For some reason I'm not getting email alerts on this repo. Will fix that and address this issue asap.

**Comment by timvieira** [comment]
Have a look at the command-line argument documentation, i.e., ``$ python vocrf/tagfail.py --help``.
Let me know if there is anything else I can do to make this command-line argument clearer!

**Comment by bratao** [comment]
Thank you!

**Comment by timvieira** [comment]
No! Thank you for helping me improve this code! Keep the issues coming! 😁
